[package]
name = "cryptopals"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "*", default-features = false, features = [] }
base64 = { version = "*", default-features = false, features = ["std"] }
hex = { version = "*", default-features = false, features = ["alloc"] }
